/**
 * 英语助手 - 扩展词书数据
 * A2/B2/C2 三个 CEFR 补充等级 + 六类考试词书
 * (A1=TIER1, B1=TIER2, C1=TIER3 存于 wordFrequency.js)
 */

function parse(raw) {
  return new Set(
    raw.replace(/\n/g, '').split(',')
      .map(w => w.trim().toLowerCase())
      .filter(Boolean)
  );
}

// ── A2 初级（日常生活常用词，约 500 词）──────────────────────────────
const A2_RAW = `aboard,accident,address,agree,alarm,angry,apologize,arrive,aunt,awful,
backpack,bake,ball,barbecue,beard,bedroom,bench,biscuit,blind,boil,borrow,
bright,bug,calm,cart,ceiling,celebrate,channel,chase,cheap,cherry,chicken,
circus,cliff,clue,coach,coat,collect,comfort,compass,complain,connect,cookie,
copy,countryside,couple,cousin,creek,curly,cycle,danger,decoration,
depart,dessert,diary,diet,direct,dolphin,drama,driver,earn,embarrass,
emergency,enemy,engage,enter,escape,event,exciting,factory,fail,fairy,fancy,
fashion,feather,fence,fill,float,flour,folder,forecast,galaxy,giant,grateful,
grocery,hill,hobby,hook,horizon,horror,hug,hunt,identical,illness,
interview,invite,jealous,joke,jungle,kettle,landlord,lately,launch,library,
liquid,magazine,marble,marine,memory,message,midnight,miracle,mixture,mop,
muscle,neighbor,nervous,nightmare,obey,ocean,ordinary,organize,outline,
overcome,overnight,parcel,path,pepper,perform,permit,phrase,picnic,plate,
plenty,possess,prefer,price,pride,puzzle,queue,recipe,recycle,reflect,relax,
release,remind,repair,rescue,reserve,rinse,risk,routine,runway,sailor,scary,
screen,selfish,shiver,signal,skill,sleeve,slice,slide,somebody,spare,spend,
spill,stamp,strange,style,sunrise,suspicious,swing,temple,thankful,ticket,
tidy,tiny,topic,tourist,treasure,tribe,twinkle,umbrella,unfair,uniform,usual,
valley,vehicle,volunteer,voyage,warehouse,wedding,worried,yacht,zone,
above,across,adult,advice,after,again,almost,alone,along,already,always,
among,amount,animal,another,apart,apply,area,around,arrive,ask,away,
back,basically,beach,become,before,behind,below,beside,between,beyond,
busy,carry,catch,cause,check,choose,clean,clear,climb,close,cold,corner,
date,decide,describe,draw,drive,during,else,enjoy,even,every,explain,
face,fall,feed,fetch,fight,find,fine,finish,fix,follow,forward,free,
garden,give,glad,guess,hang,happen,hard,hate,heavy,high,hold,honest,
hotel,hurry,inside,invite,jump,keep,kind,know,large,late,laugh,lead,
learn,leave,less,lift,like,listen,live,local,long,look,loud,low,magic,
manage,maybe,meet,mind,miss,mostly,mouth,near,never,noise,once,open,
outside,over,pack,paint,park,pass,pay,pick,plan,play,point,pull,push,
quite,raise,reach,ready,real,remember,reply,return,ride,rise,round,rush,
same,save,search,send,sharp,shop,shout,sing,sleep,smell,smile,soft,sorry,
sort,speak,stand,stay,still,stop,strong,sure,take,talk,teach,tend,till,
tired,together,touch,toward,trust,turn,until,usually,warm,watch,wide,
wish,wonder,wrong,yard,young`;

// ── B2 中高级（上中级复杂话题词汇，约 600 词）────────────────────────
const B2_RAW = `accommodate,accomplish,aggressive,ambition,anxiety,apparent,appreciate,
arbitrary,aspect,aspire,assert,asset,automatic,awareness,boundary,capable,
career,caution,citizen,compensate,competent,comprehensive,concept,confidence,
conform,consistent,convert,crucial,decline,defense,deficit,deployment,
depression,dominate,elaborate,enormous,enterprise,enthusiastic,establish,
evolution,exceed,exclusive,execute,exhibit,exploit,external,facilitate,
feedback,frustrate,fundamental,guarantee,guidance,ignorance,impressive,
incentive,incorporate,inevitable,influential,initiate,innovative,insight,
intensive,interactive,interfere,investigate,isolation,launch,limitation,
loyalty,manufacture,mechanism,minority,motivate,navigate,neutral,occupation,
overcome,permanent,precise,procedure,prominent,proportion,psychology,pursue,
rational,realistic,requirement,resistance,responsible,restrict,revenue,reward,
stability,substantial,survival,terminate,transaction,undermine,unprecedented,
utility,versatile,widespread,workforce,abstract,achieve,acquire,adapt,adequate,
adjust,administration,advocate,agenda,aggressive,allocate,alter,ambiguous,
analyze,annual,apparent,approach,appropriate,assembly,assign,assist,assume,
attribute,authorize,benefit,capacity,category,circumstance,cite,civil,
classify,collaborate,commence,commit,communicate,complex,component,concentrate,
conduct,consequence,contribute,convention,cooperate,coordinate,corporate,
correlate,cycle,debate,decade,define,demonstrate,detect,dimension,distribute,
document,draft,economy,element,emerge,emphasize,enable,enforce,enhance,ensure,
entity,estimate,evaluate,eventually,evolve,exclude,expand,explicit,export,
expose,extend,extract,feature,federal,finance,focus,formula,foundation,
framework,generate,grant,guideline,identify,ignore,implement,imply,indicate,
individual,initial,institutional,integrate,interpret,invest,isolate,justify,
layer,license,likewise,maintain,maximum,mechanism,minimum,modify,monitor,
notion,obtain,occur,outcome,output,overall,overlap,perceive,phase,policy,
portion,principal,promote,proportion,publish,purchase,range,ratio,recover,
reduce,reform,regulate,reinforce,reject,release,rely,resolve,restrict,retain,
reveal,revise,secure,seek,select,sequence,shift,specify,stable,strategy,
submit,substitute,sufficient,summary,survey,sustain,target,technique,tension,
theme,transfer,transform,trigger,ultimate,uniform,valid,verify,version,
welfare,whereas,whereby`;

// ── C2 精通（高阶稀有词汇，约 600 词）────────────────────────────────
const C2_RAW = `abate,abdicate,aberrant,abhor,abstain,abstruse,acrimony,adamant,adulation,
alacrity,alleviate,amalgamate,ameliorate,anachronism,antipathy,archaic,arduous,
ascetic,assuage,assiduous,attenuate,audacity,austere,avarice,bombastic,brevity,
cacophony,capricious,censure,circumspect,cogent,complaisant,conciliate,
condescending,confound,convoluted,culpable,dearth,defiance,deride,desultory,
discrepancy,disdain,disparate,dogmatic,dubious,eccentric,elusive,emulate,
endemic,enigmatic,equivocate,evanescent,exacerbate,exonerate,expedient,
exquisite,fastidious,fervent,flagrant,fledgling,formidable,fortitude,frugal,
futile,garrulous,gratuitous,guileless,heretical,hubris,hyperbole,impede,
ingenuous,insidious,insolent,intractable,juxtapose,laborious,laconic,latent,
laud,lenient,lucid,malevolent,manifest,meticulous,mundane,nefarious,nostalgic,
obstinate,omnipresent,ostracize,parity,partisan,pervasive,placate,poignant,
precarious,precipitate,presumptuous,proclivity,proliferate,provocative,rancor,
recalcitrant,reprehensible,rigorous,scrutinize,skeptical,subvert,superficial,
supplant,tenacious,turbulent,ubiquitous,vacuous,vehement,zealous,
abdomen,aberration,abjure,abnegate,abrogate,abstemious,accede,accolade,
accretion,acumen,adroit,adulterate,adversarial,aesthetic,affable,aggregate,
aghast,aloof,altruistic,ambivalent,ameliorate,anachronism,analogous,anarchy,
annihilate,anomalous,antithetical,apathy,appease,archetype,ardent,ascendancy,
assiduous,atrocious,atrophy,augment,aversion,avid,banal,befuddle,belittle,
bellicose,benevolent,bias,blatant,bolster,burnish,calculated,callous,candid,
captivate,charlatan,chronic,circumvent,clandestine,coerce,coherent,
commensurate,compel,concede,condone,contentious,copious,corroborate,
counterfeit,covert,credulous,cryptic,cunning,deceitful,deference,deliberate,
delusion,denounce,depict,deplore,derivative,devious,differentiate,dignified,
diligent,diminish,discern,dismiss,displace,dissent,distort,diverse,dominant,
dynamic,egregious,eliminate,empower,enigma,ephemeral,erratic,ethical,evolve,
exemplify,exhaustive,exert,exhaustive,explicit,exploit,fabricate,facile,
fallacy,fervent,fervor,finite,flaunt,fluctuate,foresee,frugality,genuine,
grievous,guile,hamper,harsh,hinder,humility,hypocrite,ideology,illuminate,
imminent,impartial,impeccable,impulsive,inadequate,inclusive,inexorable,
infer,inherent,initiative,innate,intrinsic,invincible,irony,litigious,lofty,
malleable,mediocre,methodical,minimize,mitigate,moderate,morose,naive,
negligent,nominal,notorious,nuanced,nurture,obscure,obstruct,ominous,opaque,
opportunistic,oppressive,ostensible,paradox,patronize,peculiar,persevere,
pertinent,plausible,pragmatic,prejudice,pretentious,prevalent,proficient,
proliferation,proponent,prudent,radical,rationale,rectify,redundant,refute,
reinstate,relentless,remedial,renounce,repudiate,resolute,rhetoric,robust,
ruthless,sanctimonious,satirical,shrewd,skepticism,sophisticated,speculate,
sporadic,stagnant,steadfast,stoic,strenuous,stringent,subjective,substantiate,
subtle,systematic,tactical,tenacious,timid,transparent,unanimous,unequivocal,
validate,viable,virtuous,volatile,vulnerable,wary,withhold`;

// ── CET4 大学英语四级（约 2000 词）────────────────────────────────────
const CET4_RAW = `abandon,ability,absence,absolute,absorb,abstract,abundant,academic,accept,
access,accomplish,accurate,achieve,acknowledge,acquire,active,actual,adapt,
adequate,admire,adopt,advance,advantage,afford,agency,alert,allocate,alter,
analyze,announce,annual,apologize,apparent,apply,approve,arrange,aspect,assess,
assign,assist,assume,assure,attach,attempt,attitude,attract,authority,aware,
balance,bargain,basis,behave,benefit,biology,boring,bother,bound,brief,budget,
capable,capacity,capture,care,case,casual,category,cause,celebrate,challenge,
chapter,character,chemical,choose,circumstance,cite,claim,clarify,classify,
college,combine,commit,communicate,compare,compete,concentrate,conduct,confirm,
conflict,confuse,consist,construct,contact,continue,contrast,contribute,
control,convert,cooperate,create,criteria,culture,current,declare,defeat,
define,demonstrate,depend,depict,design,detail,develop,devote,differ,
discipline,display,distribute,divide,earn,economy,educate,effect,elect,
element,eliminate,employ,encourage,enterprise,establish,estimate,evaluate,
evidence,evolve,exceed,excite,exercise,expand,explain,express,extend,
facility,factor,feature,field,finance,flexible,focus,formal,forward,function,
generate,genuine,global,goal,graduate,guarantee,guidance,honest,humorous,
identify,illustrate,impact,improve,include,indicate,individual,industry,
inform,initial,innovate,inspire,integrate,interpret,investigate,involve,
justify,launch,lawyer,legal,locate,logical,maintain,majority,manage,
measure,minor,monitor,motivate,nature,necessary,negotiate,network,normal,
notice,objective,observe,obtain,official,operate,opportunity,option,organize,
original,outline,participate,perform,period,permit,policy,potential,predict,
prevent,primary,principle,process,produce,project,promote,propose,protect,
prove,provide,pursue,qualify,realize,recognize,recommend,reflect,reinforce,
remain,revise,schedule,secure,seek,select,separate,significant,solve,specify,
staff,standard,status,subject,substitute,suggest,supply,support,survey,
sustain,task,technique,tend,threat,topic,transfer,transform,trend,trust,
utilize,variety,verify,volume,wealth,withdraw,yield,ability,absence,abstract,
achieve,acquire,adapt,administration,advocate,affect,agency,agenda,agree,
alcohol,alert,align,allocate,alternative,ambitious,analyze,anniversary,
anticipate,apology,apparently,apply,appreciate,appropriately,argument,arise,
arrangement,article,assess,assign,attitude,authorize,balance,behavior,biology,
blame,boundary,budget,calculate,capable,capacity,catalog,cause,celebrate,
certainly,challenge,chapter,characteristic,chemical,choice,citation,civil,
clarify,classification,colleague,collect,column,combine,comfort,command,
commerce,communicate,community,complete,complex,component,concentrate,conclude,
conduct,confidence,confirm,conflict,conscious,consist,construct,contact,
content,contemporary,continue,convention,convince,cooperate,correct,create,
culture,curriculum,cycle,damage,deal,debate,decide,declare,define,deliberate,
deliver,demand,demonstrate,depend,derive,design,determine,develop,differ,
difficulty,diminish,directly,discipline,discuss,display,distribute,doubt,
draft,drama,dynamic,economy,education,effective,efficient,element,emerge,
employ,encourage,engage,enhance,enjoy,ensure,evaluate,evident,examine,
example,exceed,exercise,exhibit,expand,explain,express,factor,fashion,favor,
feature,finance,flexible,fluent,focus,fortunately,function,furniture,gap,
gather,global,grade,grateful,growth,guarantee,guide,handle,highlight,host,
identify,illustrate,image,impact,important,improve,income,increase,indicate,
industry,influence,inform,insight,inspire,institute,interact,interpret,invest,
involve,issue,judgment,justify,knowledge,landscape,link,locate,logical,
maintain,manage,material,maximum,method,minimum,mission,mode,monitor,
motivate,multiple,negotiate,normal,notice,objective,obtain,operate,option,
organize,outcome,output,participate,perform,permit,perspective,phase,policy,
practical,predict,prefer,prevent,principle,priority,process,professional,
progress,promote,propose,protect,provide,publish,pursuit,quality,question,
realize,receive,recognize,recommend,record,reduce,refer,reform,regulate,
reject,relationship,release,rely,remain,remove,require,research,respond,
retain,reveal,revise,role,routine,satisfy,schedule,secure,seek,select,
sequence,serve,settle,significant,simplify,solve,specify,staff,state,
strategy,structure,success,suggest,summarize,supply,survey,target,technique,
tend,theory,topic,transfer,transform,treat,typical,understand,upgrade,utilize,
variable,verify,version,view,vision,volunteer,welfare,whether,yield,
abolish,accommodate,accomplish,accurate,acknowledge,additionally,adequate,
admiration,adoption,advancement,advertise,affection,allocate,allowance,
alternative,approval,aspiration,atmosphere,attribution,authorization,
automatically,availability,beneficial,calculation,capability,celebration,
chronological,circumstance,classification,collaboratively,communication,
concentration,conclusion,constitution,contribution,conventional,coordination,
creativity,criticism,declaration,dedication,deliberation,demonstration,
departmental,dependence,development,dimension,disappointment,discipline,
discussion,distinction,distribution,effectively,elaboration,elimination,
employment,encouragement,establishment,evaluation,eventually,examination,
exception,exhibition,explanation,expression,extension,formation,freedom,
government,graduation,guarantee,guidance,hypothesis,identification,
illustration,importance,improvement,indication,individual,innovation,
inspiration,institution,integration,intelligence,interpretation,investment,
investigation,involvement,justification,knowledge,legislation,maintain,
management,measurement,minority,organization,participation,performance,
prediction,prevention,primarily,priority,production,progression,protection,
provision,publication,qualification,recommendation,reflection,regulation,
rejection,relationship,remainder,requirement,response,revelation,selection,
significance,specification,standardization,structure,substitution,suggestion,
sustainability,transformation,translation,understanding,utilization,variation,
verification,visualization,volunteerism`;

// ── CET6 大学英语六级（约 1500 词）────────────────────────────────────
const CET6_RAW = `accumulate,aesthetic,aggravate,ambiguous,analogous,anonymous,anticipate,
apprehension,assimilate,autonomy,bias,circumstance,collaborate,commence,
compatible,complement,compliance,confront,constitute,controversial,conviction,
coordinate,correlate,credibility,criterion,cumulative,diminish,discourse,
displace,distort,divergent,dynamic,eliminate,empirical,enhance,equivalent,
ethical,formulate,hypothesis,ideology,implicit,inconsistency,indispensable,
inhibit,intellectual,intermediate,intervention,invoke,magnitude,manipulation,
methodology,minimize,moderate,mutual,narrative,necessity,negotiate,network,
normative,obscure,obstruct,phenomenon,plausible,precedent,preliminary,premise,
priority,projection,qualitative,quantitative,radical,relevance,resilient,
restriction,retain,rhetoric,scenario,sequence,subsequent,supplement,
sustainability,synthesis,terminology,theoretical,threshold,transformation,
transparent,underlying,urban,validity,violation,virtual,abandon,acceleration,
accountability,accumulation,acquaintance,adolescent,affiliation,aggression,
alienation,ambivalence,amplification,antagonism,anticipation,approximation,
articulation,aspiration,assumption,attribution,bureaucracy,capitulation,
characterization,circulation,cogitation,cohabitation,collaboration,
complexity,comprehension,concentration,configuration,confrontation,
consideration,consolidation,contemplation,contradiction,controversy,
cooperation,cultivation,delegation,demonstration,determination,differentiation,
disclosure,distribution,equilibrium,exaggeration,execution,exhaustion,
facilitation,formulation,fragmentation,frustration,generalization,hierarchy,
hypothesis,identification,implication,incentive,inclination,incorporation,
indication,inference,infrastructure,innovation,integration,interpretation,
investigation,justification,legitimacy,maximization,minimization,negotiation,
normalization,objectification,observation,orientation,oscillation,participation,
perpetuation,polarization,prioritization,quantification,rationalization,
recognition,reconciliation,recovery,rectification,reflection,registration,
reinforcement,representation,resolution,responsibility,restoration,
sophistication,specification,standardization,stratification,subjection,
substantiation,systematization,terminology,utilization,verification,
visualization,abstract,accomplish,acquaint,activate,actualize,address,
adequacy,adherence,adjacent,advocate,aggregate,allocate,anticipate,
apprehend,appreciate,appropriate,arbitrary,ascertain,assemble,assess,
authorize,benchmark,calculate,capability,capitalize,categorize,characterize,
circulate,clarify,classify,coexist,collaborate,communicate,compromise,
concentrate,conceptualize,conduct,configure,consolidate,constitute,construct,
contemplate,contradict,contribute,conventionally,critically,crystallize,
customize,delineate,demonstrate,differentiate,diminish,discriminate,disrupt,
document,elaborate,eliminate,emphasize,enable,evaluate,examine,execute,
facilitate,formulate,generate,harmonize,highlight,hypothesize,identify,
implement,incorporate,innovate,institutionalize,integrate,interpret,invest,
investigate,justify,locate,maximize,mediate,minimize,mobilize,normalize,
obtain,optimize,orchestrate,participate,perpetuate,polarize,potentially,
prioritize,professionalize,quantify,rationalize,reconcile,reduce,regulate,
reinforce,represent,resolve,restore,scrutinize,standardize,stimulate,
strategize,streamline,substantiate,synthesize,systematize,theorize,transform,
utilize,validate,visualize,absurdity,accumulation,adversity,advocacy,
ambiguity,analytical,anomaly,arbitrary,axiom,benchmark,coherent,corollary,
deterioration,discourse,disparity,empiricism,exemplary,exposition,frugality,
geopolitical,hierarchical,ideological,interdependent,marginalization,
multidimensional,paradigmatic,pragmatism,proportional,systemic,vicarious`;

// ── IELTS 雅思（约 800 词）────────────────────────────────────────────
const IELTS_RAW = `academic,accommodation,analyze,approach,assess,category,challenge,clarify,
collaborate,complex,concept,conclude,context,controversial,correlate,cultural,
debate,distribute,document,dynamic,economic,element,establish,evaluate,examine,
extensive,facilitate,flexible,framework,generate,global,gradual,hypothesis,
illustrate,infrastructure,initial,initiative,investigate,legislation,logical,
methodology,multiple,objective,obtain,perspective,policy,potential,predict,
priority,procedure,promote,proportion,publish,qualify,ratio,recognize,reform,
relevant,restore,statistic,structure,summarize,sustain,technique,tradition,
transfer,underlying,utilize,vary,abandon,abstract,accessible,accumulate,
accurate,acknowledge,adaptation,administration,advocate,aesthetic,affect,
aggregate,allocate,alternative,ambitious,analyze,anticipate,appropriate,
approximate,articulate,assemble,assert,associate,assume,attribute,authorize,
autonomous,beneficial,bias,capable,capitalize,categorize,causal,characteristic,
circulation,classify,coherent,collaborate,commence,compatible,compile,
comprehend,concentrate,confine,consecutive,constitute,constraint,consult,
convert,cooperative,criteria,cumulative,decline,deduce,define,demonstrate,
denote,derive,design,determine,diminish,discriminate,displace,disrupt,distinct,
diverse,elaborate,empirical,emphasis,enable,enforce,engage,evaluate,exclude,
expose,formulate,generate,govern,guarantee,highlight,hypothesis,identify,
imply,incorporate,indicate,influence,institute,integrate,interpret,isolate,
justify,layer,maximize,minimize,moderate,monitor,mutually,obtain,occur,
outline,particular,perceive,persist,postpone,prioritize,project,publish,
pursue,qualify,rational,regardless,reinforce,relate,rely,require,restrict,
reveal,select,shift,simplify,specify,stable,stimulate,support,sustain,
target,theoretical,transfer,transform,undermine,validate,various,verify,
achieve,acquire,activate,adapt,adequately,adjust,advance,advise,aggregate,
allocate,alter,append,apply,appreciate,articulate,assemble,assess,assign,
assist,assume,authorize,calculate,categorize,challenge,characterize,classify,
collaborate,compile,conduct,consult,coordinate,create,define,deliver,demonstrate,
design,determine,develop,differentiate,direct,display,distribute,document,
elaborate,employ,facilitate,identify,implement,incorporate,indicate,inform,
initiate,justify,maintain,maximize,monitor,obtain,organize,participate,perform,
present,prioritize,process,produce,promote,qualify,recognize,reduce,regulate,
reinforce,require,research,respond,select,stimulate,structure,submit,support,
target,utilize,validate,verify,accomplish,acknowledge,adopt,assert,benchmark,
collaborate,compile,comprehend,configure,critique,customize,deduce,derive,
discriminate,emphasize,evaluate,formulate,generate,hypothesize,illustrate,
integrate,investigate,justify,legitimize,optimize,rationalize,reconcile,
standardize,systematize,theorize,validate`;

// ── TOEFL 托福（约 800 词）────────────────────────────────────────────
const TOEFL_RAW = `abstract,accommodate,accumulate,acquisition,adaptive,adjacent,adverse,
aggregate,allocate,ambiguous,annual,apparent,approximate,cite,comprehensive,
component,construct,conserve,convention,correlate,derive,detect,dimension,
diverse,element,empirical,entity,estimate,exhibit,extract,federal,formula,
fund,grade,grant,incorporate,isolate,layer,license,likewise,maximum,mechanism,
minimum,modify,notion,occur,output,overlap,perceive,phase,portion,preliminary,
projection,publish,purchase,quote,recover,reduce,reject,resolve,restrict,
retain,reveal,sequence,shift,specify,stable,submit,substitute,sufficient,
summary,terminate,theme,transform,ultimate,uniform,valid,vary,welfare,whereas,
achieve,accurate,acknowledge,adapt,adequate,adjust,advocate,affect,allocate,
alter,analyze,anticipate,apply,appropriate,approximate,assemble,assert,assess,
assign,assist,assume,assign,attribute,authorize,balance,benefit,capable,
capacity,categorize,challenge,characterize,cite,clarify,collaborate,commence,
compose,conceptualize,configure,consider,consolidate,constitute,contribute,
coordinate,criteria,decline,define,demonstrate,derive,design,determine,
differentiate,diminish,distribute,diverse,document,elaborate,eliminate,
emphasize,enable,evaluate,examine,expand,explain,expose,formulate,function,
generate,highlight,identify,imply,incorporate,indicate,influence,initiate,
integrate,interpret,investigate,justify,maintain,maximize,measure,mediate,
minimize,mobilize,monitor,negotiate,obtain,organize,outline,participate,
perceive,perform,persist,prioritize,process,produce,promote,provide,qualify,
quantify,rationalize,recognize,reconcile,reduce,regulate,reinforce,report,
require,resolve,restrict,retain,reveal,select,specify,stimulate,summarize,
support,sustain,target,theorize,transfer,transform,undermine,utilize,validate,
verify,accomplish,acquire,activate,adapt,adjust,affirm,align,allocate,assign,
associate,attribute,benefit,calculate,calibrate,categorize,challenge,classify,
collaborate,communicate,configure,consolidate,coordinate,critique,deduce,
define,demonstrate,derive,designate,differentiate,distribute,eliminate,enforce,
estimate,evaluate,execute,facilitate,formulate,generate,identify,implement,
incorporate,indicate,influence,initiate,integrate,interpret,investigate,
justify,locate,maximize,measure,minimize,mobilize,monitor,obtain,organize,
optimize,participate,perform,persist,predict,prioritize,process,produce,
project,qualify,quantify,recognize,reduce,regulate,reinforce,require,research,
resolve,restrict,select,specify,stimulate,support,sustain,theorize,utilize,
validate,verify,assimilation,categorization,characterization,comprehension,
configuration,contradiction,differentiation,elaboration,formulation,
generalization,identification,incorporation,interpretation,investigation,
maximization,minimization,observation,optimization,rationalization,specification,
substantiation,transformation,utilization,verification`;

// ── GRE 研究生入学（约 800 词）───────────────────────────────────────
const GRE_RAW = `abate,aberrant,abhor,abjure,abstain,abstruse,acrimony,adamant,adulation,
alacrity,alleviate,ambivalent,ameliorate,anachronism,antipathy,arduous,artless,
ascetic,assuage,assiduous,attenuate,audacity,austere,avarice,bombastic,brevity,
capricious,censure,circumspect,cogent,complaisant,conciliate,condescending,
confound,convoluted,culpable,dearth,defer,deride,desultory,discrepancy,disdain,
disparate,dogmatic,dubious,eccentric,elusive,endemic,enigmatic,equivocate,
evanescent,exacerbate,exonerate,expedient,fastidious,fervent,flagrant,fortitude,
frugal,futile,garrulous,gratuitous,guileless,heretical,hubris,hyperbole,impede,
ingenuous,insidious,insolent,intractable,juxtapose,laborious,laconic,latent,
lenient,lucid,malevolent,manifest,meticulous,mundane,nefarious,nostalgic,
obstinate,ostracize,parity,partisan,pervasive,placate,poignant,precarious,
precipitate,presumptuous,proclivity,proliferate,provocative,rancor,recalcitrant,
reprehensible,rigorous,scrutinize,skeptical,subvert,supplant,tenacious,
turbulent,ubiquitous,vacuous,vehement,zealous,abdicate,abnegate,abrogate,
abstain,accolade,acumen,adroit,adulterate,aesthetic,affable,aggregate,aloof,
altruistic,ambivalent,ameliorate,analogous,anarchy,anomalous,antithetical,
apathy,appease,archetype,ardent,assiduous,atrophy,augment,aversion,avid,
banal,befuddle,belittle,bellicose,benevolent,blatant,bolster,calculated,callous,
candid,captivate,charlatan,chronic,circumvent,clandestine,coerce,coherent,
commensurate,compel,concede,condone,contentious,copious,corroborate,counterfeit,
covert,credulous,cryptic,cunning,deceitful,deference,deliberate,delusion,
denounce,deplete,deplore,derivative,devious,dignified,diligent,discern,
dissent,distort,dominant,egregious,empower,enigma,ephemeral,erratic,evolve,
exemplify,exhaustive,exert,explicit,fabricate,facile,fallacy,finite,flaunt,
fluctuate,foresee,genuine,grievous,guile,hamper,harsh,hinder,humility,
hypocrite,illuminate,imminent,impartial,impeccable,impulsive,inadequate,
inexorable,infer,inherent,innate,intrinsic,invincible,irony,lofty,malleable,
mediocre,methodical,mitigate,morose,naive,negligent,nominal,notorious,nuanced,
nurture,obstruct,ominous,opaque,oppressive,ostensible,paradox,patronize,
peculiar,persevere,pertinent,plausible,pragmatic,prejudice,pretentious,
prevalent,proficient,prudent,radical,rationale,rectify,redundant,refute,
reinstate,relentless,remedial,renounce,repudiate,resolute,rhetoric,robust,
ruthless,satirical,shrewd,skepticism,sophisticated,speculate,sporadic,stagnant,
steadfast,stoic,stringent,subjective,subtle,systematic,tactical,timid,
unanimous,unequivocal,viable,virtuous,volatile,wary,withhold,aberration,
abjuration,abrogation,accretion,acrimony,adulation,aegis,alacrity,alienation,
allusion,ambiguity,amelioration,antagonism,archetype,ardor,articulation,
aspersion,assimilation,attenuation,augmentation,aversion,bellicosity,
benevolence,blandishment,bombast,brevity,cacophony,capitulation,caricature,
charlatan,circumlocution,cogency,complacency,complicity,condescension,
confutation,contention,contrite,contumacious,culmination,culpability,
decorum,deprecation,derogation,despondency,detriment,diminution,discern,
disparagement,dissension,distortion,divergence,dogmatism,duplicity,exacerbation,
exoneration,expediency,exuberance,fabrication,fallibility,fanaticism,
fatalism,ferocity,fickleness,fluidity,forbearance,forensics,frugality`;

// ── SAT（约 600 词）───────────────────────────────────────────────────
const SAT_RAW = `advocacy,ambitious,attest,bias,coherent,comprehensive,conform,contemplate,
controversial,convince,determine,deviate,effective,examine,explicit,expose,
generate,identify,indicate,inference,inherent,insight,justify,logical,
manipulate,narrate,objective,observe,obtain,outcome,perceive,phenomenon,
perspective,preliminary,proportion,rational,recognize,reflect,reinforce,
relevant,reveal,scrutinize,sophisticated,speculate,substantial,sustain,
theoretical,transformation,underlying,valid,variable,widespread,eloquent,
eminent,impartial,moderate,plausible,precise,prevalent,rigorous,skeptical,
subjective,systematic,verify,vulnerable,abandon,abstract,academic,accessible,
accurate,analyze,assert,assess,authentic,challenge,characterize,cite,classify,
collaborate,compare,complex,conclude,conduct,consider,context,contradiction,
critique,debate,deduce,define,demonstrate,derive,differentiate,disagree,
discriminate,disrupt,diverse,document,elaborate,eliminate,emphasize,empirical,
evaluate,examine,explain,explore,express,facilitate,formulate,generate,
highlight,hypothesize,identify,illustrate,imply,incorporate,indicate,infer,
influence,innovate,interpret,investigate,justify,maintain,manifest,measure,
modify,objective,optimize,organize,outline,perceive,prioritize,qualify,
quantify,rationalize,realize,reconcile,reduce,refute,reinforce,relate,
represent,resolve,restrict,reveal,simplify,specify,stimulate,structure,
summarize,support,synthesize,transform,undermine,utilize,validate,vary,
verify,accomplish,acknowledge,acquire,adapt,adequate,adjust,advance,advocate,
affect,allocate,alter,anticipate,apply,appropriate,approximate,assemble,
attribute,authorize,balance,benefit,capable,categorize,challenge,clarify,
collaborate,commence,compile,conceptualize,configure,consolidate,coordinate,
criteria,define,demonstrate,design,develop,differentiate,distribute,elaborate,
employ,enable,evaluate,expand,facilitate,identify,incorporate,indicate,
integrate,interpret,investigate,justify,maximize,minimize,monitor,obtain,
participate,perform,prioritize,process,produce,promote,qualify,recognize,
regulate,reinforce,require,research,resolve,select,specify,stimulate,
support,sustain,target,theorize,transfer,utilize,validate,verify,
abstraction,antagonism,articulation,assertion,assumption,categorization,
characterization,clarification,collaboration,complication,comprehension,
configuration,contradiction,critique,deduction,demonstration,differentiation,
elaboration,evaluation,exemplification,formulation,generalization,hypotheses,
identification,implication,incorporation,integration,interpretation,
investigation,justification,quantification,rationalization,reconciliation,
specification,substantiation,summarization,transformation,utilization`;

const A2_SUPPLEMENTAL_RAW = `ability,able,abroad,accept,accident,activity,actor,advice,afford,
afraid,age,agree,airline,airport,album,alive,amazing,anymore,anyway,anywhere,area,
artist,asleep,assistant,attack,audience,available,avoid,backpack,basic,basket,
bathroom,battery,beach,bean,bear,beat,bedroom,believe,bell,bill,biology,blanket,
board,boat,borrow,boss,brave,bridge,brush,burn,cage,camp,candle,capital,careful,
castle,catch,celebration,century,champion,cheap,cheer,chemistry,choice,church,
circle,clear,clever,cloud,coast,college,comfortable,company,competition,condition,
conversation,cook,cooker,cool,copy,corner,costume,cotton,count,crowd,customer,
daily,dangerous,darkness,deadline,decision,degree,delicious,dentist,department,
dictionary,difference,difficult,digital,direction,discover,distance,document,download,
earring,education,electric,electricity,entrance,environment,especially,excellent,
exhibition,experience,experiment,familiar,famous,fantastic,favorite,festival,flight,
foreign,forest,forget,friendship,garage,gas,gentle,goal,government,habit,headline,
healthy,heating,history,holiday,hopeful,however,hungry,impossible,information,
instrument,interest,international,journalist,journey,kindness,knowledge,laptop,
lawyer,leader,leather,lecture,leisure,lie,location,luggage,manager,meal,member,
mention,method,middle,missing,motorcycle,movement,national,natural,necessary,
neighbor,normal,opinion,opportunity,opposite,passenger,perfect,perhaps,photograph,
physical,pilot,planet,pleasant,pocket,polite,popular,population,position,possible,
poster,practice,prefer,prepare,private,probably,program,project,promise,protect,
public,queen,quietly,realistic,receive,record,recycle,regular,repair,report,
responsible,review,screen,secret,sentence,serious,service,shoulder,similar,simple,
somewhere,special,stranger,successful,suddenly,suitcase,survive,teenager,theater,
tourism,traffic,training,translation,traveler,trouble,useful,usually,vacation,
valuable,video,waiter,waitress,website,without,wonderful`;

const B2_SUPPLEMENTAL_RAW = `abnormal,absorb,acceleration,acceptable,accessible,accountability,
accurately,adaptation,administrative,admission,adolescent,adoption,advancement,
adverse,advertising,affection,affordability,alignment,ambivalence,analytical,
anniversary,anxiety,applicable,approval,architecture,artificial,assessment,
association,atmosphere,attachment,attribution,availability,bargain,biological,
briefly,bureaucratic,capability,chronological,collaboration,colonial,commodity,
compensate,competence,complexity,complication,comprehensive,concentration,
conclusion,configuration,confirmation,congress,consciousness,conservation,
considerable,consistent,consultation,consumption,contemporary,contradiction,
controversy,cooperation,creativity,credibility,criticism,cultivation,curiosity,
dedication,defensive,delegation,democratic,departure,dependence,description,
detection,disability,disappointment,disclosure,discrimination,displacement,
disposal,distinctive,diversity,ecological,effectiveness,efficiency,elaboration,
employment,encouragement,engagement,engineering,entitlement,environmental,
equality,equilibrium,exception,exclusively,executive,exhaustion,expectation,
experimental,exposure,extension,facilitation,foundation,fragmentation,frequency,
fulfillment,functional,generalization,governance,hierarchy,identification,
immigration,implementation,implication,inclusion,increasingly,independence,
industrial,inference,infrastructure,institution,intervention,introduction,
leadership,legislation,legitimate,maintenance,manufacturing,migration,
negotiation,obligation,observation,orientation,partnership,perception,
permission,presentation,productivity,qualification,reconstruction,registration,
reliability,representation,resolution,restriction,retirement,satisfaction,
significance,stimulation,strategic,strengthen,subsequent,substitution,
technological,transition,uncertainty,unemployment,variation,visibility`;

const C2_SUPPLEMENTAL_RAW = `abject,abstemious,acquiesce,admonish,affinity,aggrandize,anodyne,
antediluvian,apocryphal,apologist,apostate,appeasement,approbation,arrogate,
asperity,assail,astute,banality,benign,bilious,calumny,candor,capitulate,
catharsis,caustic,chicanery,coalesce,commiserate,compendium,conciliatory,
conflagration,conjecture,connive,consecrate,conspicuous,contrition,conundrum,
convivial,corporeal,debacle,debilitate,decadent,decorous,defunct,deference,
deleterious,delineate,demagogue,demur,denigrate,diatribe,didactic,diffident,
dilettante,disabuse,discerning,discomfit,disingenuous,disinterested,disparage,
dissolution,ebullient,eclectic,efface,effrontery,egotistical,elicit,emollient,
enervate,entreat,epistemology,equivocal,erudite,esoteric,excoriate,exculpate,
exigent,extant,facetious,fecund,felicitous,florid,foible,forlorn,fortuitous,
fractious,gainsay,grandiloquent,hackneyed,iconoclast,ignominious,impecunious,
imperious,implacable,inchoate,incisive,incongruous,indolent,ineffable,
ingratiate,inimical,inscrutable,interlocutor,intransigent,inveterate,irascible,
judicious,largesse,lassitude,mawkish,mendacious,mercurial,modicum,nebulous,
obdurate,obfuscate,obsequious,panacea,paragon,pedantic,penchant,penury,
perfunctory,pernicious,perspicacious,phlegmatic,polemical,prodigal,propensity,
protean,pugnacious,pusillanimous,quixotic,rarefied,recondite,reprobate,
rescind,reticent,salient,sanguine,scintillating,solicitous,spurious,stolid,
surreptitious,taciturn,tendentious,trenchant,truculent,turgid,umbrage,
vicissitude,vilify,vitriolic,voluble,winsome`;

const CET4_SUPPLEMENTAL_RAW = `absolute,absorb,acceptable,accident,account,accuse,achievement,
address,adjustment,admission,adult,advertisement,advertising,advice,affair,
agreement,agriculture,aid,airline,airport,allow,amaze,amount,ancestor,anger,
ankle,anxiety,anyway,appeal,appearance,appointment,argument,army,arrival,
assignment,atmosphere,average,background,basically,battle,beauty,belief,billion,
branch,brand,brilliant,broad,business,camera,campaign,candidate,careful,central,
ceremony,channel,charge,childhood,circle,climate,collection,comfortable,common,
competition,complaint,connection,consumer,conversation,creative,customer,daily,
dangerous,database,deadline,delivery,department,disease,download,drug,electric,
electronic,emergency,emotion,engine,entertainment,environment,equipment,error,
especially,excellent,exchange,experience,experiment,expert,familiar,foreign,
frequency,friendship,generation,geography,grammar,historical,identity,immediate,
improvement,independent,injury,insurance,internet,interview,introduction,journey,
journal,leader,learning,literature,location,magazine,manager,marketing,marriage,
meaningful,medicine,memory,message,mistake,negative,occasion,ordinary,passenger,
patient,payment,photograph,planet,pleasant,politician,positive,possibility,
preparation,pressure,professor,pronunciation,proposal,reasonable,reception,
reference,regular,relative,request,restaurant,scientist,secretary,shopping,
similarity,speaker,special,statement,strength,suitable,surprise,temperature,
tourism,tourist,transport,university,useful,valuable,vehicle,visitor,warning,
willing,writer`;

const CET6_SUPPLEMENTAL_RAW = `abnormal,absorption,adaptation,administrative,admission,adverse,
advocacy,affordability,alignment,analytical,applicable,architecture,artificial,
assessment,association,attachment,bureaucratic,coherent,commodity,compensation,
competence,consciousness,conservation,considerable,consultation,consumption,
contingent,conventional,cooperative,correspondence,credibility,deduction,
democratic,depression,detection,disability,discretion,disposal,distinctive,
ecological,effectiveness,efficiency,empirical,entitlement,environmental,
equality,exception,exclusively,executive,expectation,experimental,exposure,
functional,governance,ideological,immigration,inclusion,independence,industrial,
influential,interactive,interference,legitimate,maintenance,migration,neutrality,
obligation,perception,permission,prospective,recipient,reliability,strategic,
strengthen,substantial,technological,transition,uncertainty,unemployment,
visibility`;

const IELTS_SUPPLEMENTAL_RAW = `accommodation,adaptability,adequacy,administrative,advocacy,
affordability,agriculture,alternative,analytical,approximately,assessment,
availability,awareness,beneficial,biodiversity,capability,carbon,coastal,
commodity,community,comparison,compensation,competence,consequence,conservation,
considerable,consumption,contribution,conventional,cooperative,creativity,
credibility,criterion,cultural,decline,demographic,dependency,disability,
discrimination,diversity,domestic,ecological,efficiency,emission,employment,
energy,environmental,equilibrium,estate,ethical,evidence,expenditure,exposure,
financial,foundation,functional,gender,governance,household,immigration,impact,
industrial,inequality,integration,interaction,international,maintenance,
migration,minority,nuclear,nutrition,obligation,overall,partnership,poverty,
productivity,reliability,resident,resource,rural,significant,solar,strategic,
subsidy,transportation,urbanization,vehicle,wellbeing`;

const TOEFL_SUPPLEMENTAL_RAW = `adaptation,adjacent,advocate,agricultural,ancestor,archaeology,
architecture,artifact,astronomy,atmospheric,biodiversity,biological,botany,
carbon,celestial,climate,coastal,colony,commodity,compound,conservation,consume,
continental,crust,deforestation,density,deposition,desertification,domesticate,
ecosystem,erosion,evolutionary,extinction,fossil,genetic,geological,glacier,
habitat,hemisphere,indigenous,industrial,instinct,latitude,lava,magnetic,mammal,
marine,meteorite,migration,mineral,molecule,nutrient,organism,particle,plateau,
predator,prehistoric,primate,radiation,reproductive,reservoir,sediment,solar,
species,substance,tectonic,terrestrial,territory,vegetation,volcanic,watershed`;

const GRE_SUPPLEMENTAL_RAW = `abject,abstemious,acquiesce,admonish,aggrandize,anodyne,apocryphal,
apostate,approbation,arrogate,asperity,assail,astute,banality,benign,bilious,
calumny,candor,capitulate,catharsis,caustic,chicanery,coalesce,commiserate,
compendium,conjecture,connive,consecrate,contrition,conundrum,convivial,
corporeal,debacle,debilitate,decadent,decorous,defunct,deleterious,demagogue,
demur,denigrate,diatribe,didactic,diffident,dilettante,disabuse,discomfit,
disingenuous,disinterested,disparage,ebullient,efface,effrontery,egotistical,
elicit,enervate,entreat,erudite,esoteric,excoriate,exculpate,exigent,extant,
facetious,fecund,felicitous,florid,foible,forlorn,fractious,gainsay,
grandiloquent,hackneyed,iconoclast,ignominious,impecunious,imperious,
implacable,inchoate,incisive,incongruous,indolent,ineffable,ingratiate,
inimical,inscrutable,intransigent,inveterate,irascible,judicious,largesse,
lassitude,mawkish,mendacious,mercurial,modicum,nebulous,obdurate,obfuscate,
obsequious,panacea,paragon,pedantic,penchant,penury,perfunctory,pernicious,
perspicacious,phlegmatic,polemical,prodigal,propensity,protean,pugnacious,
pusillanimous,quixotic,recondite,reprobate,reticent,sanguine,spurious,stolid,
surreptitious,taciturn,trenchant,truculent,umbrage,vicissitude,vilify,vitriolic`;

const SAT_SUPPLEMENTAL_RAW = `aberration,abstraction,accountable,adaptation,adversity,advocacy,
alienation,ambiguity,analogy,analysis,antagonism,approximation,argumentation,
assumption,authenticity,capitulation,characterization,circulation,coherence,
comparison,comprehension,concession,configuration,connotation,consequence,
consideration,consistency,contextual,contradictory,controversy,correlation,
credibility,deductive,defensible,deliberation,denotation,descriptive,
deterioration,disparity,distinction,divergence,emphasis,empirical,exemplary,
exposition,generalization,hypothetical,ideological,implication,inferential,
interpretive,legitimacy,metaphor,nuance,objectivity,paradoxical,plausibility,
precedent,qualification,reasoning,relevance,representative,resolution,
rhetorical,significance,substantive,supposition,synthetic,validity`;

const GENERAL_EXAM_SUPPLEMENTAL_RAW = `accompany,accountant,accuracy,achievement,adjustable,
administrator,admission,advantageous,advertise,affection,agricultural,aircraft,
alcohol,allergic,ambulance,anniversary,anxious,appliance,applicant,appointment,
architect,athlete,attendant,automatic,automobile,backward,baggage,balanced,barrier,
behavioral,belonging,beneficial,biography,blank,blessing,border,broadcast,calculator,
calendar,campus,carpenter,carriage,cartoon,casual,celebrated,cellphone,championship,
cheerful,chemical,childish,commercial,commuter,companion,competitive,complimentary,
composer,confident,congratulation,consumer,container,continent,convenient,coordinator,
copyright,counselor,creative,currency,customs,deadline,decoration,delightful,dentistry,
dependent,designer,desperate,detective,diagram,diploma,directory,disaster,discount,
display,domestic,donation,dramatic,drawer,educational,effective,electrical,elevator,
embarrassed,emotional,employee,encouraging,engineer,entertaining,entrance,envelope,
environment,essential,exceptional,excitement,exhausted,expensive,experienced,
explanation,explorer,expression,fantasy,fascinating,federal,financial,firefighter,
flexibility,formal,fortunate,foundation,freedom,frequent,frightened,frustrated,
functional,furthermore,generous,geographical,graduation,guardian,handwriting,
headquarters,helpful,historical,household,illustration,imagination,immigrant,
impressive,independently,industrial,informal,injured,inspector,instruction,
intelligent,intention,interesting,interpreter,invitation,jewelry,journalism,keyboard,
laboratory,landscape,leadership,lecturer,license,literary,manufacturer,mathematics,
mechanical,membership,microphone,misunderstand,nationality,neighborhood,occupation,
officially,operator,organization,originally,participant,particularly,partnership,
passionate,performance,personality,photography,political,portable,possibility,
practical,presentation,printer,professional,pronunciation,property,publication,
qualified,realistic,recommendation,refrigerator,relationship,religious,remarkable,
representative,reservation,responsibility,scholarship,scientific,secondary,signature,
specialist,spectacular,stadium,statement,successful,surrounding,technical,technology,
traditional,transportation,unfortunately,uniform,universal,valuable,variation,voluntary`;

const COMMON_ACADEMIC_SUPPLEMENTAL_RAW = `abstraction,accountability,accumulation,adaptability,
adequacy,adjacency,administration,allocation,analogy,analyst,anomaly,applicability,
approximation,assembly,assessment,availability,behaviorism,capability,classification,
coincidence,collaboration,commodity,comparative,compatibility,compensation,competency,
complexity,conditional,configuration,connectivity,consciousness,conservation,
consistency,consultancy,contingency,contradictory,coordination,correlation,
credibility,criterion,cultivation,deductive,dependency,designation,destination,
deterioration,diagnosis,differential,discrimination,displacement,disruption,
diversification,documentation,economical,elaboration,empirical,equivalence,
evaluation,evolutionary,expenditure,experimental,explanatory,feasibility,
fluctuation,functionality,generalization,hierarchical,homogeneous,hypothetical,
ideological,implementation,implication,inadequacy,inclusion,incompatibility,
inconsistency,incremental,indication,inequality,inference,infrastructure,innovation,
institutional,interaction,interdependence,interpretive,interrelationship,
legitimacy,manipulation,methodological,multidisciplinary,necessity,normalization,
objectivity,orientation,paradigm,parameter,phenomenal,pragmatism,precondition,
predictive,probability,productivity,proportional,proposition,qualitative,
quantitative,rationality,reconstruction,redistribution,regulatory,reliability,
replication,representation,resilience,statistical,substantive,supplementary,
sustainability,symbolic,systematic,terminological,theoretical,transparency,
underpinning,variability,verification,viability`;

const ADVANCED_EXAM_SUPPLEMENTAL_RAW = `abrogate,abstemious,acclimate,acquiescence,admonition,
affability,aggrandizement,amorphous,anathema,antagonistic,apotheosis,arbitrate,
ascendancy,assimilate,auspicious,avaricious,belie,benediction,blithe,boorish,
burgeon,byzantine,canonical,capacious,celerity,chauvinism,circumscribe,
circumvent,coercion,compunction,conflation,confluent,congenial,consequential,
construe,contiguous,contravene,corroboration,cosmopolitan,credence,daunting,
debilitation,decimation,deferential,demarcate,denunciation,derision,diffidence,
dissonance,divest,docile,eclecticism,efficacy,egregiousness,elucidate,emancipate,
empathy,encomium,encumber,ephemeral,epitome,equanimity,equivocation,exacerbation,
exalt,exoneration,extrapolate,fastidiousness,flippant,forestall,galvanize,
germane,gregarious,harangue,hegemony,iconoclastic,ignominy,impartiality,
imperturbable,implacability,impropriety,incendiary,indifference,infallible,
ingenuousness,inhibit,insularity,inundate,irrevocable,juxtaposition,kinship,
lament,languid,legion,magnanimous,magnate,maladroit,manifestation,marginal,
metaphysical,misanthrope,mitigation,oblivious,orthodox,ostentation,pacify,
parochial,partisanship,peripheral,permeate,perniciousness,placation,platitude,
postulate,pragmatic,precipitation,prescient,probity,profligate,prolific,
propitiate,propriety,quandary,reciprocal,redress,refutation,relegate,remonstrate,
replete,reproach,resignation,reticence,sagacious,scruple,sedulous,solace,
stratagem,subjugate,subversive,superfluous,supposition,sycophant,tacit,temerity,
transient,unassailable,unobtrusive,veneration,veracity,verbose,vindicate`;

const ACADEMIC_TOPIC_SUPPLEMENTAL_RAW = `acid,adaptable,adulthood,affluent,agriculturalist,
alteration,archaeological,arid,artwork,bacterium,barometer,beverage,breed,canal,
cardiovascular,carnivore,cartography,ceramic,chronicle,civilization,coalition,
combustion,communal,compost,congestion,constellation,contaminate,coral,corridor,
counterpart,craftsmanship,creature,crop,cultivate,deficiency,demolish,deposit,
dessert,deterioration,diagrammatic,digest,dimension,disperse,disposal,dividend,
drought,ecology,educator,emigrate,emission,endangered,erosion,evacuate,evaporation,
evolution,excavation,expedition,faculty,fauna,fertile,fertilizer,flourish,folklore,
fossil,fungus,habitation,harvest,heritage,horticulture,humidity,hygiene,illiteracy,
indoor,inhabit,inhabitant,irrigation,jurisdiction,landfill,landmark,livestock,
longevity,marine,metropolitan,microscope,monument,motorway,municipal,nutrition,
offspring,orbit,organic,overcrowding,oxygen,pesticide,physician,plague,pollutant,
pottery,preservation,protein,recreation,renewable,reptile,reservoir,respiratory,
restoration,sanitation,settlement,shortage,slum,species,suburb,suburban,surplus,
symptom,territorial,textile,thrive,topography,toxic,tribal,tuition,vegetation,
ventilation,vertebrate,wildlife`;

export const WORD_BOOKS = {
  a2:    parse(`${A2_RAW},${A2_SUPPLEMENTAL_RAW}`),
  b2:    parse(`${B2_RAW},${B2_SUPPLEMENTAL_RAW},${COMMON_ACADEMIC_SUPPLEMENTAL_RAW}`),
  c2:    parse(`${C2_RAW},${C2_SUPPLEMENTAL_RAW},${ADVANCED_EXAM_SUPPLEMENTAL_RAW}`),
  cet4:  parse(`${CET4_RAW},${CET4_SUPPLEMENTAL_RAW},${GENERAL_EXAM_SUPPLEMENTAL_RAW}`),
  cet6:  parse(`${CET6_RAW},${CET6_SUPPLEMENTAL_RAW},${COMMON_ACADEMIC_SUPPLEMENTAL_RAW},${ADVANCED_EXAM_SUPPLEMENTAL_RAW}`),
  ielts: parse(`${IELTS_RAW},${IELTS_SUPPLEMENTAL_RAW},${COMMON_ACADEMIC_SUPPLEMENTAL_RAW},${ACADEMIC_TOPIC_SUPPLEMENTAL_RAW}`),
  toefl: parse(`${TOEFL_RAW},${TOEFL_SUPPLEMENTAL_RAW},${COMMON_ACADEMIC_SUPPLEMENTAL_RAW},${ACADEMIC_TOPIC_SUPPLEMENTAL_RAW}`),
  gre:   parse(`${GRE_RAW},${GRE_SUPPLEMENTAL_RAW},${ADVANCED_EXAM_SUPPLEMENTAL_RAW}`),
  sat:   parse(`${SAT_RAW},${SAT_SUPPLEMENTAL_RAW},${COMMON_ACADEMIC_SUPPLEMENTAL_RAW},${ADVANCED_EXAM_SUPPLEMENTAL_RAW}`),
};
