/**
 * 英语单词频率分级数据
 * TIER1: 最常见 ~900 词（基础级，不高亮）
 * TIER2: 常见 ~2000 词（初级，不高亮）
 * TIER3: 较常见 ~2500 词（中级，不高亮）
 * 不在任何层级的单词 = 难词，可选高亮
 */

const TIER1_RAW = `
the,a,an,and,or,but,if,in,on,at,to,for,of,with,by,from,up,about,into,through,
before,after,above,below,between,out,off,over,under,along,around,down,near,
across,behind,beside,beyond,inside,outside,toward,within,without,
because,since,while,although,though,unless,until,as,that,whether,nor,
i,me,my,mine,myself,you,your,yours,yourself,he,him,his,himself,she,her,hers,herself,
it,its,itself,we,us,our,ours,ourselves,they,them,their,theirs,themselves,
who,whom,whose,which,what,this,those,these,
all,some,any,both,each,every,either,neither,none,nobody,somebody,anybody,everybody,
nothing,something,anything,everything,
not,no,so,too,very,just,also,even,still,already,yet,soon,often,always,never,
here,there,when,where,why,how,then,now,again,well,
one,two,three,four,five,six,seven,eight,nine,ten,eleven,twelve,
thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen,twenty,
thirty,forty,fifty,sixty,seventy,eighty,ninety,hundred,thousand,million,
first,second,third,fourth,fifth,sixth,seventh,eighth,ninth,tenth,
monday,tuesday,wednesday,thursday,friday,saturday,sunday,
january,february,march,april,may,june,july,august,september,october,november,december,
be,is,am,are,was,were,been,being,
have,has,had,do,does,did,done,
will,would,could,should,might,can,must,shall,
say,said,says,get,got,make,made,go,went,gone,come,came,
see,saw,seen,know,knew,known,take,took,taken,think,thought,look,want,
give,gave,given,find,found,tell,told,ask,feel,felt,try,keep,kept,let,
seem,show,hear,heard,play,live,call,move,turn,mean,meant,
start,stop,read,write,open,close,run,stand,sit,walk,talk,
help,like,love,put,bring,hold,carry,leave,pass,use,work,set,eat,drink,
become,became,buy,bought,send,sent,spend,spent,lose,lost,
build,built,win,won,meet,met,break,broke,broken,
good,bad,great,big,small,large,little,high,low,long,short,
old,new,young,right,wrong,true,false,hard,easy,fast,slow,
hot,cold,warm,cool,light,dark,free,clear,full,empty,
important,different,same,real,possible,early,late,
red,blue,green,black,white,yellow,brown,gray,orange,purple,pink,
happy,sad,angry,afraid,ready,able,nice,fine,strong,weak,
rich,poor,busy,safe,healthy,many,much,few,less,more,most,
another,other,own,sure,
time,year,people,way,day,man,woman,child,world,life,
hand,part,place,home,work,thing,number,word,name,
water,food,money,house,room,door,floor,window,wall,street,
car,road,land,air,fire,night,morning,school,book,
family,father,mother,son,daughter,brother,sister,friend,
head,body,eye,ear,nose,mouth,arm,leg,heart,
city,town,area,side,end,line,level,form,type,kind,
game,team,point,minute,hour,week,month,age,course,fact,
war,story,law,power,language,case,reason,result,
idea,question,answer,example,change,plan,system,
country,group,problem,government,state,
able,action,actually,agree,ago,alive,almost,alone,among,amount,
appear,apply,argue,back,base,catch,cause,check,choose,
class,clean,close,condition,control,cost,cover,cut,deal,deep,
describe,draw,drive,during,else,enough,enter,face,fall,
far,fight,fill,fine,finish,fit,follow,forget,forward,full,
give,glad,grow,guess,happen,hold,hope,human,join,
lack,large,late,lead,learn,long,low,main,matter,maybe,mind,
mostly,need,once,plan,point,possible,pull,raise,reach,
realize,remember,rise,round,same,seem,send,several,side,
since,size,small,sorry,speak,stand,stay,still,stop,strong,
teach,tend,toward,turn,until,usually,voice,watch,wide,wish,
yet,ahead,almost,among,apart,back,care,carry,catch,change,
choose,class,clean,close,drop,enjoy,even,every,field,
finish,free,give,grow,happen,hard,hear,keep,kind,know,
leave,less,like,listen,live,local,look,loud,low,
manage,meet,mind,miss,move,need,never,nice,noise,offer,
open,pack,paint,park,pass,pay,pick,plan,play,pull,push,
quite,raise,reach,ready,real,ride,rush,save,search,share,
sing,sleep,smell,smile,soft,speak,try,warm,watch
`;

const TIER2_RAW = `
allow,appear,apply,argue,attend,avoid,believe,borrow,cause,check,choose,chose,chosen,
claim,collect,compare,complete,consider,contain,control,create,decide,describe,develop,
discover,discuss,drive,drove,driven,explain,express,fail,fall,fell,follow,forget,forgot,
forgotten,gain,grow,grew,guess,happen,hate,hit,imagine,improve,include,increase,involve,
join,kill,laugh,learn,listen,manage,mention,miss,notice,offer,perform,prepare,present,
produce,prove,pull,push,reach,realize,receive,recognize,remember,remove,reply,report,
represent,require,return,rise,rose,save,serve,share,speak,spoke,spoken,suggest,suppose,
support,teach,taught,test,throw,threw,thrown,touch,train,travel,treat,understand,understood,
visit,vote,wait,warn,watch,wear,wore,wonder,worry,sell,sold,lead,led,
action,activity,addition,amount,analysis,article,attention,authority,base,behavior,
business,challenge,chance,character,choice,class,community,company,condition,conference,
control,cost,culture,deal,decision,degree,design,detail,difference,direction,discussion,
distance,division,effort,election,energy,environment,evidence,experience,figure,force,
future,glass,goal,growth,history,image,impact,individual,industry,information,institution,
issue,knowledge,management,market,material,meaning,media,method,mind,model,moment,
movement,nature,network,news,note,office,opportunity,option,organization,paper,pattern,
performance,period,position,pressure,price,process,product,project,property,purpose,
quality,rate,record,region,relationship,religion,response,risk,role,science,security,
sense,service,situation,society,source,space,stage,standard,structure,success,surface,
task,technology,term,theory,thought,trade,training,trial,understanding,union,unit,
value,variety,view,vision,voice,weight,
actual,additional,available,aware,basic,certain,close,commercial,complex,current,deep,
direct,effective,entire,essential,exact,existing,final,former,full,general,global,human,
individual,international,legal,local,major,medical,military,modern,national,natural,
necessary,normal,official,original,particular,personal,physical,political,popular,
potential,previous,primary,private,professional,public,recent,relevant,serious,similar,
significant,single,social,specific,successful,traditional,typical,unique,various,wide,
already,around,behind,beyond,during,especially,exactly,finally,generally,however,instead,
likely,mostly,nearly,otherwise,particularly,perhaps,rather,recently,simply,sometimes,
suddenly,therefore,together,towards,usually,within,without,
access,account,achieve,acquire,adapt,addition,adequate,adjust,adopt,advance,
advantage,affect,afford,agenda,allocate,alter,analyze,announce,apply,appreciate,
approve,arise,arrange,assess,assign,assist,assume,assure,attach,attempt,
attract,authority,balance,benefit,capable,capacity,capture,celebrate,
certify,chapter,character,chemical,choose,circumstance,cite,clarify,classify,
colleague,combine,commit,communicate,compare,compete,concentrate,conduct,
confirm,conflict,confuse,consist,construct,contact,contribute,convert,
cooperate,coordinate,declare,defeat,define,demonstrate,depend,design,detail,
devote,differ,discipline,display,distribute,divide,educate,elect,eliminate,
employ,encourage,establish,estimate,evaluate,evolve,exceed,exercise,expand,
facilitate,factor,feature,finance,flexible,focus,function,generate,genuine,
goal,graduate,guarantee,guidance,identify,illustrate,indicate,inform,initial,
inspire,integrate,interpret,investigate,involve,justify,launch,maintain,
majority,manage,measure,minor,monitor,motivate,negotiate,observe,obtain,
operate,organize,original,participate,perform,permit,policy,predict,prevent,
principle,process,produce,promote,propose,protect,pursue,qualify,recommend,
reflect,reinforce,remain,revise,schedule,secure,seek,select,separate,solve,
specify,staff,standard,status,subject,substitute,supply,sustain,technique,
topic,transfer,transform,trend,utilize,variety,verify,volume,wealth,yield,
ability,absence,abstract,academic,accomplish,accurate,acknowledge,
administration,advocate,affect,agency,agree,alert,alternative,ambitious,
annual,anticipate,apparently,appropriate,argument,arrangement,article,attitude,
authorize,behavior,biology,blame,boundary,budget,calculate,capability,
catalog,celebrate,certainly,citation,civil,classification,column,comfort,
command,commerce,complete,component,conclude,confidence,connection,conscious,
contemporary,convention,convince,correct,curriculum,cycle,damage,debate,
deliberate,deliver,demand,denote,derive,determination,difficulty,directly,
doubt,drama,dynamic,efficient,emerge,engage,enhance,ensure,evident,
examine,exhibit,expose,fashion,favor,fluent,formal,fortunately,furniture,
gather,grateful,handle,highlight,host,income,industry,influence,insight,
institute,interact,judgment,landscape,link,locate,logical,maximum,minimum,
mission,mode,multiple,objective,outline,perspective,phase,practical,prefer,
priority,professional,progress,provide,publication,pursuit,question,recognize,
reduce,reform,regulate,reject,relationship,rely,research,respond,retain,
reveal,role,routine,satisfy,sequence,settle,simplify,solve,state,strategy,
structure,suggest,target,tend,theory,typical,understand,upgrade,variable,
view,vision,volunteer,welfare,whether
`;

const TIER3_RAW = `
achieve,acquire,adapt,adequate,adjust,administration,adopt,advantage,
affect,agenda,allocate,alter,amendment,analyze,annual,apparent,approach,
appropriate,approximate,assembly,assess,assign,assist,assume,attach,attribute,
budget,capable,capacity,category,chapter,chart,cite,civil,classify,code,
commit,communicate,component,concentrate,concept,conduct,consequence,contract,
contribute,convention,convert,corporate,correspond,cycle,data,debate,decade,
define,demonstrate,detect,dimension,distribute,document,dominant,draft,dynamic,
economy,element,emerge,emphasize,enable,encounter,enforce,enhance,ensure,entity,
estimate,evaluate,eventually,evolve,exclude,exhibit,expand,explicit,export,expose,
extend,external,extract,facilitate,feature,federal,finance,focus,format,formula,
foundation,framework,function,fund,generate,grade,grant,guideline,hypothesis,
identify,ignore,implement,imply,indicate,initial,integrate,interpret,invest,
isolate,justify,layer,license,likewise,maintain,maximum,mechanism,minimum,modify,
monitor,notion,objective,obtain,occur,outcome,output,overall,overlap,parameter,
perceive,phase,policy,portion,principal,procedure,promote,proportion,protect,
publish,purchase,quote,range,ratio,recover,reduce,refer,reform,regulate,
reinforce,reject,release,rely,research,resolve,restrict,retain,reveal,revenue,
revise,secure,seek,select,sequence,shift,specify,stable,strategy,stress,submit,
substitute,sufficient,summary,survey,sustain,target,technique,tension,theme,
transfer,transform,trend,trigger,ultimate,undertake,uniform,utilize,valid,
verify,version,volume,welfare,whereas,whereby,
accurate,achievement,acknowledge,advisory,aggregate,comprehensive,constitute,
controversial,cooperative,demonstrate,dependence,derived,diverse,empirical,
enhance,equivalent,ethical,evaluate,fundamental,global,hypothesis,inherent,
innovative,interpretation,investigate,methodology,mutual,paradigm,perspective,
preliminary,rational,relevant,theoretical,underlying,variable,comprehensive,
contemporary,correlation,critical,cumulative,deduction,demographic,derived,
distribution,empirical,flexible,hierarchy,hypothesis,implicit,inductive,
infrastructure,initiative,innovation,institutional,integrate,intervention,
legislative,legitimate,marginal,normative,notion,orientation,output,
pragmatic,precede,premise,priority,projection,qualitative,quantitative,
rational,regulatory,reinforce,sequential,specification,subordinate,
supplement,synthesis,transformation,transparent,underlying,validation,
abandon,accelerate,access,accomplish,accurate,acknowledge,active,actual,
adapt,adequate,admire,adopt,advance,advantage,afford,agency,allocate,
announce,anticipate,application,appreciate,approve,arise,arrange,aspect,
assemble,assert,associate,attribute,authorize,autonomous,balance,beneficial,
calculate,capture,categorize,challenge,characterize,circulate,clarify,
collaborate,commence,compatible,compile,comprehend,configure,constitute,
constraint,consult,coordinate,criteria,decline,deduce,deliver,demand,
denote,derive,design,determine,differentiate,discriminate,displace,disrupt,
distinct,elaborate,emphasis,enable,engage,evaluate,exclude,expose,formulate,
govern,highlight,imply,incorporate,influence,initiate,institutionalize,
legitimize,mobilize,negotiate,normalize,occur,optimize,orchestrate,
persist,postpone,potentially,prioritize,professionalize,publish,rationalize,
reconcile,reduce,reinforce,relate,restrict,select,shift,simplify,
stimulate,streamline,substantiate,systematize,theorize,undermine,validate,
accommodate,accumulate,aesthetic,aggravate,ambiguous,analogous,anonymous,
apprehension,assimilate,autonomy,bias,circumstance,collaborate,compliance,
complement,confront,conviction,coordinate,credibility,criterion,diminish,
discourse,distort,divergent,eliminate,equivalent,ethical,formulate,ideology,
implicit,inconsistency,indispensable,inhibit,intellectual,intermediate,
intervention,invoke,magnitude,manipulation,minimize,moderate,narrative,
normative,obscure,obstruct,phenomenon,plausible,precedent,premise,
qualitative,quantitative,radical,relevance,resilient,restriction,retain,
rhetoric,scenario,subsequent,supplement,sustainability,synthesis,terminology,
threshold,transparent,urban,validity,violation,virtual,
abbreviate,abolish,accommodate,accountability,accrual,acquaint,activate,
actualize,address,adherence,affiliation,aggregate,alienate,amplify,antagonize,
anticipate,articulate,aspire,attribute,benchmark,capitalize,causal,characterize,
coexist,collaborate,communicate,compromise,conceptualize,confer,configure,
consolidate,contemplate,contradict,conventionally,critically,crystallize,
customize,delineate,differentiate,diminish,discriminate,disrupt,elaborate,
eliminate,emphasize,enable,evaluate,execute,harmonize,hypothesize,implement,
incorporate,institutionalize,integrate,investigate,mobilize,normalize,
orchestrate,participate,perpetuate,polarize,prioritize,professionalize,
quantify,rationalize,reconcile,regulate,reinforce,represent,restore,
scrutinize,standardize,stimulate,strategize,streamline,substantiate,synthesize
`;

const TIER1_SUPPLEMENTAL_RAW = `
apple,baby,bag,balloon,bath,bathroom,bed,bike,bird,birthday,boat,bottle,bowl,box,bread,
breakfast,bus,cake,camera,card,cat,chair,cheese,coat,coffee,computer,cup,dinner,dog,
dress,egg,evening,fish,flower,fruit,girl,glass,grandfather,grandmother,hat,homework,
juice,kitchen,knife,lunch,map,milk,music,parent,party,pen,pencil,phone,photo,picture,
plane,restaurant,rice,shoe,shop,table,taxi,tea,teacher,telephone,television,train,
tree,vegetable,weather,zoo,actor,artist,baker,bank,beach,bicycle,bill,bridge,calendar,
camp,capital,castle,cinema,clock,cloud,club,coat,concert,doctor,dream,driver,email,
farm,farmer,film,forest,garden,guest,holiday,hospital,hotel,island,jacket,job,key,
lesson,letter,market,meeting,mountain,museum,newspaper,nurse,office,park,passport,
police,present,river,song,sport,station,store,student,ticket,traffic,trip,village,
visitor,website,airport,animal,apartment,banana,basket,bath,beef,beer,belt,blanket,
boots,brush,butter,candle,candy,cap,carrot,cell,church,coat,coin,corner,cow,dance,
desk,dish,duck,elephant,engine,evening,exam,fan,festival,finger,football,fork,fridge,
gift,guitar,hair,horse,internet,lamp,lemon,letter,medicine,mirror,monkey,moon,orange,
page,pair,pants,paper,pepper,plant,plate,pocket,potato,rain,river,salad,salt,ship,
shirt,sky,snow,soup,star,summer,sun,sweater,swim,teeth,tomato,tooth,towel,uncle,
vacation,weekend,wife,winter,wood
`;

const TIER2_SUPPLEMENTAL_RAW = `
absent,acceptance,accident,advertisement,agreement,airport,analysis,announcement,
appointment,argument,arrival,association,background,beautiful,belong,billion,borrow,
branch,brilliant,campaign,candidate,careful,celebrity,central,ceremony,channel,
charge,childhood,climate,collection,comfortable,committee,common,competition,
complaint,completely,condition,connection,conversation,creative,customer,daily,
dangerous,deadline,delivery,department,description,development,digital,director,
discovery,disease,education,employee,employer,engineering,entertainment,equipment,
excellent,experiment,expert,expression,failure,familiar,financial,foreign,frequent,
friendly,generation,geography,governmental,grammar,headline,historical,immediately,
improvement,independent,interview,introduction,journey,journal,leader,learning,
location,magazine,manager,marketing,marriage,meaningful,medical,member,memory,
message,mistake,necessary,negative,normally,occasion,opinion,ordinary,passenger,
patient,payment,personal,photograph,physical,planning,pleasant,politician,positive,
possibility,preparation,professor,pronounce,proposal,protection,reasonable,recently,
reception,reference,regular,relative,request,respect,restaurant,scientist,secretary,
shopping,similarity,speaker,special,speech,statement,strength,suitable,surprise,
teaching,temperature,tourism,tourist,transport,university,useful,valuable,vehicle,
visitor,warning,willing,writer,abroad,absolutely,accept,accuse,advise,apologize,
appoint,arrive,belong,celebrate,complain,congratulate,deliver,depend,disagree,
encourage,explore,graduate,impress,injure,introduce,invite,organise,pronounce,
publish,replace,request,respect,retire,review,succeed,suffer,survive,translate,
volunteer,whisper,admiration,adventure,affair,apartment,appearance,application,
appointment,attraction,battery,beauty,belief,birth,blood,brain,career,ceremony,
citizen,climate,coal,coast,comment,communication,competition,complaint,consumer,
conversation,courage,credit,crime,customer,damage,death,delivery,description,
development,direction,disease,dream,education,electricity,engine,equipment,error,
expression,failure,flight,friendship,furniture,habit,health,interview,journey,
library,machine,marriage,medicine,message,mistake,opinion,patient,payment,peace,
photograph,population,preparation,prize,promise,purpose,reference,repair,request,
respect,review,secret,skill,speech,stranger,suggestion,temperature,tradition,
transport,university,visitor,wealth
`;

const TIER3_SUPPLEMENTAL_RAW = `
abrupt,accessible,accountable,adaptation,adjacent,administrative,adverse,advocacy,
affiliation,ambivalence,analytical,anomaly,applicable,arbitrary,articulation,
aspiration,assertion,assumption,attain,automate,autonomy,benchmark,bureaucracy,
coherent,cohesion,coincide,collapse,commodity,comparable,compensation,competence,
complexity,compliance,complication,configuration,confirmation,consensus,
conservative,consideration,consistent,consultation,contingent,contradiction,
controversy,corollary,credibility,criterion,cultivation,deduction,delegation,
deployment,designate,deteriorate,differentiation,disclosure,disparity,disposal,
diversity,documentation,elaboration,empiricism,endure,equilibrium,exemplary,
exposition,feasible,fragmentation,generalization,hierarchical,ideological,
implication,inclination,inference,infrastructure,innovation,interdependent,
legitimacy,manipulate,marginalization,mediate,migration,multidimensional,
neutrality,observation,orientation,paradigmatic,participation,perpetuation,
polarization,precedent,probability,proportional,proposition,prospective,
recipient,reconstruction,registration,resolution,speculation,stratification,
subjection,systemic,vicarious,viability,accretion,adversity,alienation,
amplification,antagonism,approximation,assimilation,capitulation,circulation,
cogitation,collaboration,confrontation,consolidation,contemplation,delegation,
determination,displacement,exaggeration,exhaustion,facilitation,formulation,
hierarchy,incorporation,intervention,legislation,maximization,minimization,
negotiation,normalization,objectification,oscillation,prioritization,
rationalization,reconciliation,rectification,representation,restoration,
sophistication,substantiation,systematization,termination,urbanization,
visualization
`;

function parseWords(raw) {
  return new Set(
    raw.split(",")
      .map(w => w.trim().toLowerCase())
      .filter(Boolean)
  );
}

export const TIER1 = parseWords(`${TIER1_RAW},${TIER1_SUPPLEMENTAL_RAW}`);
export const TIER2 = parseWords(`${TIER2_RAW},${TIER2_SUPPLEMENTAL_RAW}`);
export const TIER3 = parseWords(`${TIER3_RAW},${TIER3_SUPPLEMENTAL_RAW}`);

/**
 * 返回单词所在层级（1/2/3），或 null（不在列表中 = 难词）
 */
export function getWordTier(word) {
  const w = word.toLowerCase();
  if (TIER1.has(w)) return 1;
  if (TIER2.has(w)) return 2;
  if (TIER3.has(w)) return 3;
  return null;
}

/**
 * 判断是否为难词（不在常见词列表中，且长度 >= 4）
 */
export function isDifficultWord(word) {
  if (word.length < 4) return false;
  return getWordTier(word) === null;
}
